<?php

namespace App\Support;

/**
 * Stable API error codes for frontend handling.
 */
final class ApiErrorCode
{
    public const AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';

    public const AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE';

    public const AUTH_ACCOUNT_NOT_READY = 'AUTH_ACCOUNT_NOT_READY';

    public const AUTH_TOO_MANY_ATTEMPTS = 'AUTH_TOO_MANY_ATTEMPTS';

    public const AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED';

    public const AUTH_PASSWORD_CHANGE_REQUIRED = 'AUTH_PASSWORD_CHANGE_REQUIRED';

    public const ACCESS_FORBIDDEN = 'ACCESS_FORBIDDEN';

    public const ACCESS_WRONG_INTERFACE = 'ACCESS_WRONG_INTERFACE';

    public const ACCESS_CONTENT_DENIED = 'ACCESS_CONTENT_DENIED';

    public const EXAM_NOT_AVAILABLE = 'EXAM_NOT_AVAILABLE';

    public const EXAM_ALREADY_ATTEMPTED = 'EXAM_ALREADY_ATTEMPTED';

    public const EXAM_ATTEMPT_FINISHED = 'EXAM_ATTEMPT_FINISHED';

    public const EXAM_ATTEMPT_EXPIRED = 'EXAM_ATTEMPT_EXPIRED';

    public const EXAM_INVALID_ANSWER = 'EXAM_INVALID_ANSWER';

    public const EXAM_INCOMPLETE_ANSWERS = 'EXAM_INCOMPLETE_ANSWERS';

    public const EXAM_SUBMISSION_CLOSED = 'EXAM_SUBMISSION_CLOSED';

    public const COMPETITION_NOT_AVAILABLE = 'COMPETITION_NOT_AVAILABLE';

    public const COMPETITION_ALREADY_ATTEMPTED = 'COMPETITION_ALREADY_ATTEMPTED';

    public const COMPETITION_ATTEMPT_EXPIRED = 'COMPETITION_ATTEMPT_EXPIRED';

    public const COMPETITION_RESULT_NOT_RELEASED = 'COMPETITION_RESULT_NOT_RELEASED';

    public const COMPETITION_INVALID_ANSWER = 'COMPETITION_INVALID_ANSWER';

    public const QUESTIONNAIRE_NOT_AVAILABLE = 'QUESTIONNAIRE_NOT_AVAILABLE';

    public const QUESTIONNAIRE_ALREADY_SUBMITTED = 'QUESTIONNAIRE_ALREADY_SUBMITTED';

    public const QUESTIONNAIRE_RESPONSE_EXPIRED = 'QUESTIONNAIRE_RESPONSE_EXPIRED';

    public const QUESTIONNAIRE_INVALID_ANSWER = 'QUESTIONNAIRE_INVALID_ANSWER';

    public const MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND';

    public const MEDIA_ACCESS_DENIED = 'MEDIA_ACCESS_DENIED';

    public const MEDIA_INVALID_UPLOAD = 'MEDIA_INVALID_UPLOAD';

    public const ADMIN_SUPER_REQUIRED = 'ADMIN_SUPER_REQUIRED';

    public const ADMIN_SCOPE_DENIED = 'ADMIN_SCOPE_DENIED';

    public const ADMIN_PASSWORD_CONFIRM_REQUIRED = 'ADMIN_PASSWORD_CONFIRM_REQUIRED';

    public const VALIDATION_FAILED = 'VALIDATION_FAILED';

    public const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';

    public const RESOURCE_CONFLICT = 'RESOURCE_CONFLICT';

    public const SERVER_ERROR = 'SERVER_ERROR';
}
